### ISSUE TITLE
Change homepage copy

### ISSUE THREAD

**Issue by phrz** [cntgrd/server#13]
Copy reads:

> Nobody should have to choose between a budget and power when exploring the world of weather. Centigrade is building an affordable, connected weather station for hobbyists and data nerds alike.

Should read:

> Nobody should have to choose between **affordability** and power when exploring the world of weather. Centigrade is building an affordable, connected weather station for hobbyists and data nerds alike.

It's either a [Parallel Structure](https://owl.english.purdue.edu/owl/resource/623/01/) issue or just the fact that everyone has a budget, whether it's large or constrained, whereas affordability is explicitly the condition of something being compatible with a constrained budget.

**Comment by andy-rash** [comment]
fixed with [9557029](https://github.com/cntgrd/server/commit/95570299d6741b389a3bea05f92dea1e54e24788)
